### ISSUE TITLE
autoperf.rb:98:in `step': step can't be 0 (ArgumentError)

### ISSUE THREAD

**Issue by robrwo** [igrigorik/autoperf#4]
I've followed the instructions in the README, and I get the following error:

```
$ ruby autoperf.rb -c autoperf.conf 
autoperf.rb:98:in `step': step can't be 0 (ArgumentError)
    from autoperf.rb:98:in `run'
    from autoperf.rb:21:in `initialize'
    from autoperf.rb:113:in `new'
    from autoperf.rb:113:in `<main>'
```

**Comment by igrigorik** [comment]
Make sure your config specifies the right config variables: low_rate, high_rate, rate_step.

**Comment by igrigorik** [comment]
Also, you may be interested in: https://github.com/jmervine/autoperf

**Comment by robrwo** [comment]
That seems to work better, thanks.
