### ISSUE TITLE
URL in Description is broken

### ISSUE THREAD

**Issue by davidsonfellipe** [igrigorik/autoperf#5]
![erro](http://f.cl.ly/items/322T1z3A2d200M191D46/Screen%20Shot%202014-10-15%20at%204.30.37%20AM.png)

Correct: http://www.igvita.com/2008/09/30/load-testing-with-log-replay

**Comment by igrigorik** [comment]
good catch, thanks!

**Comment by davidsonfellipe** [comment]
@igrigorik I added autoperf in awesome-WPO, a curated list about Web Performance Optimization.

If you want to add some link just send a PR.
https://github.com/davidsonfellipe/awesome-wpo

thanks!
